### ISSUE TITLE
problem learning vst parameters

### ISSUE THREAD

**Issue by eps696** [tebjan/VVVV.Audio#106]
when several parameters of vst plugin are changed at once, 
only one of them (latest?) is visible for vst host for learning and exposing.

here is an example: https://yadi.sk/d/nuQQcZCLhF5VP
there are PadX and PadY parameters, but i cannot expose PadY.

easy way to fix it - via Info panel (all the parameters are shown there)
just selecting and exposing needed one from there, without autolearning

**Comment by tebjan** [comment]
good idea, will look into it, thanks!
