### ISSUE TITLE
WaveTable frequency and table size

### ISSUE THREAD

**Issue by sunep** [tebjan/VVVV.Audio#113]
to me, logically the wavetable synth should play back the wavetable at the frequency of the frequency input. this way a wavetable of eg. a sine wave should sound the "same" no matter how many samples it is made up off.

it does however depend on the length of the wavetable. is it a bug or a feature? if it is a feature, how many samples do I need to make it play back at the frequency set in the frequency input.

see the patch here: https://www.dropbox.com/s/3icdx1irm7zy30i/WaveTableBinSizeFreq.v4p?dl=0

Sune

**Comment by tebjan** [comment]
yes, its a bug. always relative to 1024... will fix that.
