### ISSUE TITLE
VST not workin

### ISSUE THREAD

**Issue by sunep** [tebjan/VVVV.Audio#150]
I get this error in TTY whenever I make a VSTHost node:
`00:00:35 ERR : Exception occured in TMPluginWrapperNode.Evaluate
00:00:35 ERR : Could not load type 'Sanford.Multimedia.Midi.RawMessageEventArgs' from assembly 'Sanford.Multimedia.Midi, Version=6.4.0.0, Culture=neutral, PublicKeyToken=null'.`

**Comment by tebjan** [comment]
hi sune, you need to take care which pack you use with which vvvv version because we updated the midi library and it has to be consistent across the whole vvvv installation. 35.5 needs the latest pack from the contributions. 35.2 the previous one. does that fix it?

**Comment by sunep** [comment]
that was it, it's working
