### ISSUE TITLE
Peaking in audio (little scratching) with VLAudio

### ISSUE THREAD

**Issue by karistouf** [tebjan/VVVV.Audio#176]
Hi ! i m usi,ng VLAudio with beta41x64 with 13 players running in memory. 1 is solo, and the others 12 are used  in fades from page of effect to page of effect with audio in wav 48khz. I think there is only max 5 players that may run at the same time.
It peaks also with one player playing also. Any idea any previous experiences of such a bug ? thank you

**Comment by karistouf** [comment]
i have done some tests ( having only one filstream VLAudio and not 12) and it same issues.

**Comment by joreg** [comment]
crackling sound is often caused by a too low buffer size. buffer size is a setting in your drivers properties, it cannot be changed from vvvv. so try increasing that in your drivers configuration ui.

**Comment by karistouf** [comment]
Thank you joreg, i tried before but never thing to push it up to its maximum (2048 samples). So did i this morning and it seems to work perfectly . Many thanks !!!

**Comment by joreg** [comment]
good to hear!

**Comment by karistouf** [comment]
good to read you :)
