### ISSUE TITLE
FileStream (Vaudio) will not play if Filename is invalid on startup

### ISSUE THREAD

**Issue by sunep** [tebjan/VVVV.Audio#56]
I have noticed that if the filename (possibly also Do Seek pin) is nill or does not link to a valid file on start of the patch, FileStream (Vaudio) will load but not play new files.

If you delete the FileStream node and use ctrl + Z to get it back, it works fine again.

My workaround for the moment is to let an AvoidNil default to a valid file.

Get an example patch in the thread on vvvv.org: http://vvvv.org/forum-alpha/filestream-%28vaudio%29-will-not-play-if-filename-is-invalid-on-startup

**Comment by tebjan** [comment]
should be fixed now..
