### ISSUE TITLE
Changing Waveform in Osc stops audio

### ISSUE THREAD

**Issue by sunep** [tebjan/VVVV.Audio#85]
Sometimes when changing waveform while audio is playing, it makes audio stop. it takes a reload or restart to make it work again. and it usually work with the same settings as the one that stopped the audio.

**Comment by sunep** [comment]
it seems like just patching in a subpatch can stop audio.

**Comment by sunep** [comment]
and it has happened when having a renderer go out of fullscreen

**Comment by sunep** [comment]
perhaps related, VAudio is not happy about dropbox

**Comment by tebjan** [comment]
ok, checking...

**Comment by tebjan** [comment]
related to #89
