### ISSUE TITLE
MidiMerge should be Cons (VAudio Midi)

### ISSUE THREAD

**Issue by sunep** [tebjan/VVVV.Audio#87]
MidiMerge should be Cons (VAudio Midi)

And MidiNote (VAudio Join) should be MidiNote (VAudio Midi Join) no? and it should have a corresponding split node.

and there should be equivalent MidiController nodes

**Comment by tebjan** [comment]
the cons would make two slices of midi events, the merge node really merges the midi events into one event source...

**Comment by sunep** [comment]
yes, I agree.
but I still think there should be split and join nodes

**Comment by tebjan** [comment]
yep, there is in the latest pack...
