### ISSUE TITLE
Frequency input of Osc (VAudio Source) have no effect

### ISSUE THREAD

**Issue by sunep** [tebjan/VVVV.Audio#89]
when changing the Frequency input of Osc (VAudio Source) nothing happens

**Comment by tebjan** [comment]
which pin exactly? what was connected?

**Comment by sunep** [comment]
Apparently parts of Osc died. when I made another Osc it worked fine.

see: http://vvvv.sunep.net/vvvv/Osc-Nofrequency.v4p

**Comment by tebjan** [comment]
thanks, checking...
