### ISSUE TITLE
Osc Waveforms wrong at low frequecies

### ISSUE THREAD

**Issue by sunep** [tebjan/VVVV.Audio#90]
Osc does not always produce the correct waveforms at low frequencies. At least not sawtooth, Square and Sine.
I would also argue that Noise should be slower and random, it seems like the meter is outputting some sort of averaged output.

see this patch: http://vvvv.sunep.net/vvvv/OscLowFreqWaveforms.v4p

**Comment by tebjan** [comment]
checking... Meter outputs the Max if the last buffer, that also argues for A2V #75

**Comment by tebjan** [comment]
true, changed...
